server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            response-timeout: 3s

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs/gateway
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    disable-swagger-default-url: true

services:
  auth-url: ${AUTH_SERVICE_URL:http://auth-service:8081}
  order-url: ${ORDER_SERVICE_URL:http://order-service:8082}
  payment-url: ${PAYMENT_SERVICE_URL:http://payment-service:8083}
  restaurant-url: ${RESTAURANT_SERVICE_URL:http://restaurant-service:8084}

security:
  jwt:
    issuer-uri: ${SECURITY_JWT_ISSUER_URI:connectfood-auth}
    secret: ${SECURITY_JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
